version: "1.0"
subscription:
  subscription_id: mdDe9wOPN1
  alias: spaceship
  ref: au11734
  application_type: drupal
package:
  exclude:
  - .git
  - private
  - web/sites/default/files
  - docroot/sites/default/files
  - docroot/sites/default/settings.tok.php
  - web/sites/default/settings.tok.php
