version: "1.0"
subscription:
  subscription_id: E4kz7Qq9VP
  alias: technocrat
  ref: au10015
  application_type: drupal
environment:
  environment_id: mJ5Zyoq8wN
  class: np
  dns_name: craftsperson-6163
  name: dev
  update_strategy: RollingUpdate
package:
  exclude:
  - .git
  - private
  - web/sites/default/files
  - docroot/sites/default/files
  - docroot/sites/default/settings.tok.php
  - web/sites/default/settings.tok.php
